name: Check
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
      - name: Format Check
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Check Types
        run: deno check **/*
      - name: Test
        run: deno test --coverage=coverage
      - name: Make coverage file
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          fail_ci_if_error: true
