name: Publish
on:
  push:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
      - name: Format Check
        run: deno fmt --check
      - name: Lint
        run: deno lint
      - name: Check Types
        run: deno check **/*
      - name: Test
        run: deno test
