name: Publish
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: deno task prepublish ${{ github.event.release.tag_name }}
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to JSR
        run: deno publish
